### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by mathiasertl** [pyauth/python-pkcs11#178]
Hello,

I want to use this project in my own project (https://github.com/mathiasertl/django-ca/), and just wanted to contribute to the codebase here. However there has been no releases in _four years_ and even simple PRs (e.g. #175) are no longer merged.

That makes me wonder if it still makes sense to contribute here? That would be much preferable to maintaining and publishing my own fork.

I would be willing to help to bring this project up to speed as well, if desired. I don't know how many maintainers for this are there.

**Comment by kislyuk** [comment]
Hello,

I am hoping to pick up maintenance of this project in the near future but I have encountered a number of delays. I will be sorting through pull requests shortly to prepare for a release.

**Comment by mathiasertl** [comment]
Hi @kislyuk ,

Are you open to a second maintainer in this project, maybe?

I understand you may have other responsibilities, of course, that's why multiple maintainers would benefit the project.

I'm hesitant to use the library in its current state.

Kr, Mat

**Comment by kislyuk** [comment]
@mathiasertl thank you for asking and apologies for not responding to your PR sooner. Yes, I would love to have a second maintainer here. I've sent you an invite.

**Comment by kislyuk** [comment]
After a new release is ready, I will need @danni to add one or both of us to the PyPI project (https://pypi.org/project/python-pkcs11) as she is currently the only authorized publisher.

**Comment by mathiasertl** [comment]
That's something you could ask for already.

I plan to add a few things to make this a sane Python project when I'm back from vacation (Saturday):

* GitHub actions for the tests
* type hinting
* ruff formatting/linting

Any thoughts on this?

Kr, Mat

**Comment by kislyuk** [comment]
That sounds good to me, @mathiasertl.

**Comment by mathiasertl** [comment]
Closing this, as the question is answered

**Comment by mathiasertl** [comment]
Closing this, as the question is answered
